### ISSUE TITLE
Limit max length for message attribute

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/OTPvalidationAPI#17]
Hello
One feedback following our implementation:

- we should probably limit the length of the message attribute (to 150 characters for example)
` maxLength: 150`

This is minor improvement that can probably be considered for next release.

**Comment by monamok** [comment]
@bigludo7 Isn't the max character number in SMS **160**?

**Comment by bigludo7** [comment]
Hi @monamok 
I was sure about 150 but I'm wrong - my bad.
Yes it is 160 - I change
Thanks !

**Comment by monamok** [comment]
Thank you @bigludo7

**Comment by DT-DawidWroblewski** [comment]
fixed
