### ISSUE TITLE
Send-Code API 

### ISSUE THREAD

**Issue by psidana1983** [camaraproject/OTPvalidationAPI#25]
Hi Team , 
The send-code end point uRL has 2 request parameters mobile number and  message . 
The request field message has {code} in it . 
I want to understand who generates this code ? Is it getting generated by the client and will he be responsible for appending it in the message or  the server need to generate this code and append in the message . 

Basically, is this service about only sending an SMS or generating the code and send an SMS both. 

Regards
Prashant sidana

**Comment by psidana1983** [comment]
Also, one more question what is the expected length of OTP code .

**Comment by sahidkhangithub** [comment]
@bigludo7 , can you advice on above points

**Comment by bigludo7** [comment]
We had discussion on this topic - please consider: https://github.com/camaraproject/OTPvalidationAPI/issues/24
Hope it helps.

**Comment by DT-DawidWroblewski** [comment]
all clear...

**Comment by psidana1983** [comment]
Aligned thanks
