### ISSUE TITLE
Align securitySchemes and Auth description with commonalities and ICM

### ISSUE THREAD

**Issue by fernandopradocabrillo** [camaraproject/OTPvalidationAPI#56]
**Problem description**

This API is not aligned with current ICM guidelines regarding securitySchemes and info description: [Guidelines](https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-API-access-and-user-consent.md#camara-api-specification---authorization-and-authentication-common-guidelines)

**Expected action**

Modify securityScheme to "openId" and include Athorization and Authentication section in API info.description

**Comment by AxelNennker** [comment]
info.description might be changed now that [Camara Security and Interoperability](https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-Security-Interoperability.md) document is agreed upon in ICM.

Please see
https://github.com/camaraproject/IdentityAndConsentManagement/pull/168

I suggest waiting until end-of next week with decisions regarding info.description.
